name: Build
description: 'Install macOS specific dependencies'

inputs:
  shell:
    required: false
    default: bash

runs:
  using: 'composite'
  steps:    
    - name: Install Pothosware taps
      shell:  ${{inputs.shell}}
      run: |
        brew tap pothosware/homebrew-pothos
        brew update

        # Install deps
        # soapyaudio removed from due to deprecated hamlib API
        # soapyosmo  removed because of random compilation errors
        # soapyairspyhf  removed because of random compilation errors

    - name: Install common dependencies
      shell:  ${{inputs.shell}}
      run: brew install libsndfile volk fftw soapysdr libxml2 portaudio

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: 5.14.2
        setup-python: false
        py7zrversion: '==0.18.1'

    - name: Install SoapySDR modules
      shell:  ${{inputs.shell}}
      run: brew install soapyrtlsdr soapyhackrf soapybladerf soapyairspy soapyredpitaya soapyiris limesuite soapyplutosdr

    - name: Install SoapyUHD
      shell:  ${{inputs.shell}}
      run: brew install --head soapyuhd

    - name: Download and instal SDRPlay API package
      shell: ${{inputs.shell}}
      run: |
        wget https://www.sdrplay.com/software/SDRplay_RSP_API-MacOSX-3.07.3.pkg
        sudo installer -pkg SDRplay_RSP_API-MacOSX-3.07.3.pkg -target /

    - name: Build SoapySDRPlay module from source
      shell: ${{inputs.shell}}
      run: |
        git clone https://github.com/pothosware/SoapySDRPlay3
        cd SoapySDRPlay3
        cmake -DCMAKE_BUILD_TYPE=Release -B build .
        cmake --build build
        cd build
        sudo make install
        cd ../..
