name: Build
description: 'Install macOS specific dependencies'

inputs:
  shell:
    required: false
    default: bash

runs:
  using: 'composite'
  steps:    
    - name: Remove spurious symlinks
      shell:  ${{inputs.shell}}
      run: sudo rm -f /usr/local/bin/2to3 /usr/local/bin/2to3-3.11
      
    - name: Install SoapySDR dependencies
      shell:  ${{inputs.shell}}
      run: |
        # Add custom homebrew repos
        brew tap pothosware/homebrew-pothos
        brew update
        # Install deps
        # soapyaudio removed from due to deprecated hamlib API
        # soapyosmo  removed because of random compilation errors
        # soapyairspyhf  removed because of random compilation errors
        brew install --force --overwrite libsndfile volk fftw soapysdr libxml2 portaudio
        python3 -Im pip install setuptools
        brew install --force --overwrite soapyrtlsdr soapyhackrf soapybladerf soapyairspy soapyredpitaya soapyiris limesuite soapyplutosdr
        brew install --head soapyuhd
        # TODO: needed?
        #sudo mkdir -p /usr/local/lib/SoapySDR/modules0.8
        #sudo chmod -R a+rw /usr/local/lib/SoapySDR/modules0.8
        # SDRPlay API
        wget https://www.sdrplay.com/software/SDRplay_RSP_API-MacOSX-3.07.3.pkg
        sudo installer -pkg SDRplay_RSP_API-MacOSX-3.07.3.pkg -target /
        # SoapySDRPlay3 from source
        git clone https://github.com/pothosware/SoapySDRPlay3
        cd SoapySDRPlay3
        cmake -DCMAKE_BUILD_TYPE=Release -B build .
        cmake --build build
        cd build
        sudo make install
        cd ../..


    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: 5.14.2
        setup-python: false
        py7zrversion: '==0.18.1'

